-- Ekran — içerik aktarımı (npm run aktar -- --sql ile üretildi)
-- Supabase panelinde SQL Editor'a yapıştırıp çalıştırın.
-- Tekrar çalıştırmak güvenlidir: her kayıt upsert edilir, silme yapılmaz.

begin;

-- diziler: 1 kayıt
insert into diziler (kod, veri) values
  ('eg', '{"kod":"eg","ad":"Evlilik Güzeldir"}'::jsonb)
on conflict (kod) do update set
  veri = excluded.veri;

-- bolumler: 1 kayıt
insert into bolumler (dizi, no, veri) values
  ('eg', 3, '{"dizi":"eg","no":3}'::jsonb)
on conflict (dizi, no) do update set
  veri = excluded.veri;

-- karakterler: 2 kayıt
insert into karakterler (id, dizi, veri) values
  ('nergis', 'eg', '{"id":"nergis","dizi":"eg","ad":"Nergis Aydın"}'::jsonb),
  ('sezai', 'eg', '{"id":"sezai","dizi":"eg","ad":"Sezai","notlar":"Sosyal medyada ''gonul-yolcusu'' takma hesabını kullanır."}'::jsonb)
on conflict (id) do update set
  dizi = excluded.dizi,
  veri = excluded.veri;

-- cihazlar: 3 kayıt
insert into cihazlar (kod, karakter, veri) values
  ('nergis-pc', 'nergis', '{"kod":"nergis-pc","karakter":"nergis","skin":"desktop","model":"15\" dizüstü","duvarKagidi":"duvar-kagidi-sade","rehber":[],"aramaGecmisi":[],"varsayilanDurum":{"baglanti":"normal","gorsel":"normal","saat":"21:04"}}'::jsonb),
  ('nergis-telefon', 'nergis', '{"kod":"nergis-telefon","karakter":"nergis","skin":"ios","model":"iPhone","duvarKagidi":"gece-sahil","kilitEkrani":"gece-sahil","rehber":[{"ad":"Sezai","numara":"0532 000 00 12","karakter":"sezai"},{"ad":"Anne","numara":"0533 000 00 41"},{"ad":"Elif","numara":"0535 000 00 77"},{"ad":"Kuaför","numara":"0216 000 00 09"},{"ad":"Mert","numara":"0534 000 00 58"}],"aramaGecmisi":[{"ad":"Sezai","yon":"cevapsiz","zaman":"dün 23:52","karakter":"sezai"},{"ad":"Sezai","yon":"gelen","zaman":"dün 21:14","sure":"4:12","karakter":"sezai"},{"ad":"Anne","yon":"giden","zaman":"dün 19:05","sure":"11:38"},{"ad":"Elif","yon":"gelen","zaman":"Pazartesi","sure":"1:47"},{"ad":"0216 000 00 09","yon":"cevapsiz","zaman":"Pazartesi"}],"varsayilanDurum":{"baglanti":"normal","gorsel":"normal","pil":42,"saat":"23:41","tarih":"18 Eylül Perşembe"}}'::jsonb),
  ('sezai-telefon', 'sezai', '{"kod":"sezai-telefon","karakter":"sezai","skin":"android","model":"Android telefon","duvarKagidi":"sabah-tepe","kilitEkrani":"sabah-tepe","rehber":[{"ad":"Nergis","karakter":"nergis"}],"aramaGecmisi":[],"varsayilanDurum":{"baglanti":"normal","gorsel":"normal","pil":14,"saat":"07:12","tarih":"19 Eylül Cuma"}}'::jsonb)
on conflict (kod) do update set
  karakter = excluded.karakter,
  veri = excluded.veri;

-- hesaplar: 5 kayıt
insert into hesaplar (id, dizi, modul, veri) values
  ('elif-demir', 'eg', 'sosyal', '{"id":"elif-demir","dizi":"eg","modul":"sosyal","kullaniciAdi":"elif.demir","gorunenAd":"Elif Demir","avatar":"elif.svg"}'::jsonb),
  ('gonul-yolcusu', 'eg', 'sosyal', '{"id":"gonul-yolcusu","dizi":"eg","modul":"sosyal","kullaniciAdi":"gonul_yolcusu","gorunenAd":"Gönül Yolcusu","avatar":"gonul-yolcusu.svg","karakter":"sezai"}'::jsonb),
  ('kadikoy-kahve', 'eg', 'sosyal', '{"id":"kadikoy-kahve","dizi":"eg","modul":"sosyal","kullaniciAdi":"kadikoy.kahve","gorunenAd":"Kadıköy Kahve","avatar":"kadikoy-kahve.svg"}'::jsonb),
  ('mert-kaya', 'eg', 'sosyal', '{"id":"mert-kaya","dizi":"eg","modul":"sosyal","kullaniciAdi":"mert.kaya","gorunenAd":"Mert Kaya","avatar":"mert.svg"}'::jsonb),
  ('nergis', 'eg', 'sosyal', '{"id":"nergis","dizi":"eg","modul":"sosyal","kullaniciAdi":"nergis.aydin","gorunenAd":"Nergis Aydın","avatar":"nergis.svg","karakter":"nergis"}'::jsonb)
on conflict (id) do update set
  dizi = excluded.dizi,
  modul = excluded.modul,
  veri = excluded.veri;

-- icerikler: 13 kayıt
insert into icerikler (id, dizi, tur, veri) values
  ('arama-kadikoy-kahvalti', 'eg', 'aramaSonucu', '{"tur":"aramaSonucu","id":"arama-kadikoy-kahvalti","dizi":"eg","veri":{"sorgu":"kadıköy sahilde kahvaltı","bilgi":"Yaklaşık 214.000 sonuç (0,38 saniye)","sonuclar":[{"baslik":"Kıyıda Sabah — deniz kenarında serpme kahvaltı","adres":"kiyidasabah.com › kahvalti","ozet":"Sahil yürüyüş yolunun hemen üstünde, sabah 07.00''den öğlene kadar açık. Rezervasyon hafta sonu için öneriliyor.","siteRef":"site-kiyida-sabah","gorsel":"kahve.svg"},{"baslik":"Kadıköy''de kahvaltı: sahile bakan 12 adres","adres":"gezginnotu.net › istanbul › kadikoy","ozet":"Moda''dan başlayıp sahil boyunca devam eden rotada, denize bakan masası olan yerleri derledik.","siteRef":"site-gezgin-notu","gorsel":"deniz.svg"},{"baslik":"Kadıköy Kahvaltıcı — menü ve çalışma saatleri","adres":"kadikoykahvaltici.com","ozet":"Serpme kahvaltı, kahvaltı tabağı, çay servisi. Her gün 08.00 – 14.00.","gorsel":"masa.svg"},{"baslik":"Sahilde kahvaltı nerede yapılır? — okur önerileri","adres":"rehberdefteri.net › forum › istanbul","ozet":"Forumda paylaşılan öneriler, fiyat aralıkları ve yürüme mesafesindeki alternatifler.","siteRef":"site-rehber-defteri"}],"gorseller":["kahve.svg","deniz.svg","masa.svg","sokak.svg","balkon.svg","pencere.svg"],"oneriler":["kadıköy sahil kahvaltı fiyatları","moda sahilde kahvaltı","kadıköy sabah 7 açık kahvaltı"]}}'::jsonb),
  ('elif-balkon', 'eg', 'post', '{"tur":"post","id":"elif-balkon","dizi":"eg","veri":{"hesap":"elif-demir","gorsel":"balkon.svg","aciklama":"Balkonda kitap, arkada şehir.","konum":"Moda","tarih":"dün","begeniSayisi":132,"yorumlar":[{"hesap":"nergis","metin":"Çok güzel olmuş"},{"hesap":"mert-kaya","metin":"Manzara kıskandırdı"}]}}'::jsonb),
  ('elif-kedi', 'eg', 'post', '{"tur":"post","id":"elif-kedi","dizi":"eg","veri":{"hesap":"elif-demir","gorsel":"kedi.svg","aciklama":"Komşunun kedisi yine bizde.","konum":"Moda","tarih":"2 gün","begeniSayisi":201,"yorumlar":[{"hesap":"kadikoy-kahve","metin":"Bize de uğratın"}]}}'::jsonb),
  ('kadikoy-kahve-sabah', 'eg', 'post', '{"tur":"post","id":"kadikoy-kahve-sabah","dizi":"eg","veri":{"hesap":"kadikoy-kahve","gorsel":"kahve.svg","aciklama":"Sabahın ilk demlemesi.","konum":"Kadıköy","tarih":"08:12","begeniSayisi":84,"yorumlar":[{"hesap":"elif-demir","metin":"Geliyorum birazdan ☕"}]}}'::jsonb),
  ('mert-yol', 'eg', 'post', '{"tur":"post","id":"mert-yol","dizi":"eg","veri":{"hesap":"mert-kaya","gorsel":"yol.svg","aciklama":"Yola çıkmadan son kare.","tarih":"dün","begeniSayisi":47,"yorumlar":[]}}'::jsonb),
  ('nergis-pencere', 'eg', 'post', '{"tur":"post","id":"nergis-pencere","dizi":"eg","veri":{"hesap":"nergis","gorsel":"pencere.svg","aciklama":"Bu şehir sabahları başka.","konum":"Kadıköy","tarih":"3 gün","begeniSayisi":96,"yorumlar":[]}}'::jsonb),
  ('nergis-post-cicekci', 'eg', 'post', '{"tur":"post","id":"nergis-post-cicekci","dizi":"eg","veri":{"hesap":"nergis","gorsel":"cicekci.svg","aciklama":"Bugün burada başlıyoruz.","konum":"Kadıköy","tarih":"şimdi","begeniSayisi":0,"yorumlar":[]}}'::jsonb),
  ('nergis-sezai', 'eg', 'sohbet', '{"tur":"sohbet","id":"nergis-sezai","dizi":"eg","veri":{"hesap":"gonul-yolcusu","mesajlar":[{"kim":"gonul-yolcusu","metin":"Bugünkü postunu gördüm.","saat":"23:12"},{"kim":"ben","metin":"Beğendin mi?","saat":"23:14","durum":"goruldu"},{"kim":"gonul-yolcusu","metin":"Çok. Ama konuşmamız gereken bir şey var.","saat":"23:15"},{"kim":"gonul-yolcusu","gorsel":"sokak.svg","saat":"23:16"},{"kim":"gonul-yolcusu","metin":"Bu akşam konuşmamız lazım.","saat":"23:41"}]}}'::jsonb),
  ('sezai-foto', 'eg', 'foto', '{"tur":"foto","id":"sezai-foto","dizi":"eg","veri":{"dosya":"sokak.svg","aciklama":"Sezai"}}'::jsonb),
  ('site-gezgin-notu', 'eg', 'webSayfasi', '{"tur":"webSayfasi","id":"site-gezgin-notu","dizi":"eg","veri":{"sablon":"blog","siteAdi":"Gezgin Notu","adres":"gezginnotu.net/istanbul/kadikoy","baslik":"Kadıköy''de kahvaltı: sahile bakan 12 adres","yazar":"Deniz Aksoy","tarih":"14 Eylül","menu":["İstanbul","Rota","Defter"],"renk":"#3a6b52","govde":[{"tur":"paragraf","metin":"Moda''dan başlayıp sahil boyunca yürüyerek gidilebilecek bir rota çıkardık. Listedeki yerlerin hepsinde denize bakan en az bir masa var."},{"tur":"gorsel","dosya":"deniz.svg","altYazi":"Sabah sahil yolu"},{"tur":"baslik","metin":"Rotanın başı"},{"tur":"paragraf","metin":"İlk durak iskeleye yakın; kalabalık olmadan önce sekizde masaya oturmak en iyisi. Yürüyüşün ilk yarısı gölgede kalıyor."},{"tur":"liste","maddeler":["Sabah 07.00 – 09.00 arası sakin","Hafta sonu öğleden sonra sıra oluyor","Rota boyunca yürüyüş yaklaşık 25 dakika"]},{"tur":"alinti","metin":"Deniz kenarında kahvaltının yarısı manzara, yarısı acele etmemek.","kaynak":"Deniz Aksoy"}]}}'::jsonb),
  ('site-gunluk-sehir', 'eg', 'webSayfasi', '{"tur":"webSayfasi","id":"site-gunluk-sehir","dizi":"eg","veri":{"sablon":"haber","siteAdi":"Günlük Şehir","adres":"gunluksehir.net/yasam/sahil-kahvaltisi","baslik":"Sahil kahvaltısı yeniden moda oldu","ustBaslik":"YAŞAM","yazar":"Şehir Servisi","tarih":"Bugün 08:20","menu":["Gündem","Yaşam","Kültür","Spor"],"govde":[{"tur":"paragraf","metin":"Hafta sonu sabahları sahil hattındaki kahvaltı yerlerinde yoğunluk artıyor. İşletmeciler, geçen yıla göre erken saatlerde gelen müşteri sayısının belirgin şekilde yükseldiğini söylüyor."},{"tur":"gorsel","dosya":"masa.svg","altYazi":"Sahil hattında bir kahvaltı masası"},{"tur":"baslik","metin":"Erken saatler doldu"},{"tur":"paragraf","metin":"Sabah yedi ile dokuz arası tercih edilen saat aralığı olarak öne çıkıyor. Deniz tarafındaki masalar için rezervasyon isteyen işletmelerin sayısı da artmış durumda."},{"tur":"alinti","metin":"İnsanlar artık kahvaltıya değil, sabahın kendisine geliyor.","kaynak":"Bir işletmeci"}]}}'::jsonb),
  ('site-kiyida-sabah', 'eg', 'webSayfasi', '{"tur":"webSayfasi","id":"site-kiyida-sabah","dizi":"eg","veri":{"sablon":"kurumsal","siteAdi":"Kıyıda Sabah","adres":"kiyidasabah.com/kahvalti","baslik":"Deniz kenarında serpme kahvaltı","menu":["Kahvaltı","Menü","Rezervasyon","Ulaşım"],"renk":"#2a6b7c","govde":[{"tur":"gorsel","dosya":"kahve.svg","altYazi":"Sahile bakan üst kat"},{"tur":"paragraf","metin":"Sahil yürüyüş yolunun hemen üstündeyiz. Sabah yedide açıyoruz; hafta içi öğlene, hafta sonu ikiye kadar kahvaltı veriyoruz."},{"tur":"baslik","metin":"Serpme kahvaltı"},{"tur":"liste","maddeler":["İki kişilik serpme, sınırsız çay","Köy yumurtası, menemen ya da omlet","Günlük ekmek ve ev reçelleri"]},{"tur":"baslik","metin":"Rezervasyon"},{"tur":"paragraf","metin":"Hafta sonu için rezervasyon öneriyoruz. Deniz tarafındaki masalar sınırlı sayıda; telefonla ayırtabilirsiniz."},{"tur":"alinti","metin":"Sabah erken gelin, sahil boşken kahvaltı bambaşka.","kaynak":"Kıyıda Sabah ekibi"}]}}'::jsonb),
  ('site-rehber-defteri', 'eg', 'webSayfasi', '{"tur":"webSayfasi","id":"site-rehber-defteri","dizi":"eg","veri":{"sablon":"forum","siteAdi":"Rehber Defteri","adres":"rehberdefteri.net/forum/istanbul","baslik":"Sahilde kahvaltı nerede yapılır? — okur önerileri","tarih":"Son yanıt: bugün","menu":["Forum","İstanbul"],"govde":[{"tur":"paragraf","metin":"Pazar sabahı için sahile yakın, çok kalabalık olmayan bir yer arıyorum. Yürüme mesafesinde olsun. Önerisi olan var mı?"},{"tur":"yorum","yazar":"sahilyolu","metin":"İskeleden sola doğru yürürsen üst katı olan bir yer var, sabah yedide açıyor. Erken gidersen deniz tarafına oturursun.","tarih":"2 saat önce"},{"tur":"yorum","yazar":"mavikapi","metin":"Hafta sonu ikiden sonra sıra oluyor, erken gitmekte fayda var. Fiyatlar geçen seneye göre biraz arttı ama porsiyonlar iyi.","tarih":"1 saat önce"},{"tur":"yorum","yazar":"gezginnotu","metin":"Sahil boyunca 12 adresi tek tek gezip yazmıştık, rota olarak da işe yarıyor.","tarih":"40 dakika önce"}]}}'::jsonb)
on conflict (id) do update set
  dizi = excluded.dizi,
  tur = excluded.tur,
  veri = excluded.veri;

-- sahneler: 8 kayıt
insert into sahneler (kod, dizi, bolum, veri) values
  ('eg-b03-s12', 'eg', 3, '{"kod":"eg-b03-s12","cihaz":"nergis-telefon","baslangic":{"modul":"kilit","ekran":"kilit"},"durum":{"baglanti":"normal","gorsel":"normal"},"olaylar":[{"id":"ilk-mesaj","ad":"Sezai''den ilk mesaj düşer","tetik":{"tur":"baslangic","gecikme":2500},"aksiyon":{"tur":"bildirim","uygulama":"mesaj","baslik":"Sezai","metin":"Bu akşam konuşmamız lazım."}},{"id":"ikinci-mesaj","ad":"Sezai ısrar eder","tetik":{"tur":"sonra","olayId":"ilk-mesaj","gecikme":4000},"aksiyon":{"tur":"bildirim","uygulama":"mesaj","baslik":"Sezai","metin":"Uyuyor musun?"}}],"talimat":"Telefon kilitli, masada duruyor. Sahne açıldıktan 2,5 sn sonra Sezai''den bildirim düşer, 4 sn sonra ikincisi gelir. Kumandadan elle de tetiklenebilir."}'::jsonb),
  ('eg-b03-s13', 'eg', 3, '{"kod":"eg-b03-s13","cihaz":"nergis-telefon","baslangic":{"modul":"mesaj","ekran":"sohbet","icerikRef":"nergis-sezai"},"durum":{"baglanti":"normal","gorsel":"normal","saat":"23:43"},"olaylar":[{"id":"goruldu","ad":"Sezai mesajı görür","tetik":{"tur":"baslangic","gecikme":1500},"aksiyon":{"tur":"mesajDurumu","sohbet":"nergis-sezai","durum":"goruldu"}},{"id":"yaziyor","ad":"Sezai yazmaya başlar","tetik":{"tur":"sonra","olayId":"goruldu","gecikme":2000},"aksiyon":{"tur":"yaziyor","sohbet":"nergis-sezai"}},{"id":"gelen-mesaj","ad":"Sezai''nin mesajı düşer","tetik":{"tur":"sonra","olayId":"yaziyor","gecikme":3500},"aksiyon":{"tur":"mesajGeldi","sohbet":"nergis-sezai","metin":"Yarın sabah kahvaltıda anlatırım."}},{"id":"ikinci-mesaj","ad":"Sezai devam eder","tetik":{"tur":"sonra","olayId":"gelen-mesaj","gecikme":2500},"aksiyon":{"tur":"mesajGeldi","sohbet":"nergis-sezai","metin":"Kimseye söyleme."}}],"talimat":"Sohbet ekranı açık. 1,5 sn sonra Nergis''in mesajı görüldü olur, 2 sn sonra Sezai yazmaya başlar (üç nokta), 3,5 sn sonra mesajı düşer, 2,5 sn sonra ikincisi. Replikler senaryodan alınmalı; buradakiler yer tutucudur."}'::jsonb),
  ('eg-b03-s44', 'eg', 3, '{"kod":"eg-b03-s44","cihaz":"nergis-telefon","baslangic":{"modul":"kilit","ekran":"kilit"},"durum":{"baglanti":"normal","gorsel":"normal","saat":"00:12"},"olaylar":[{"id":"arama-geliyor","ad":"Sezai arar","tetik":{"tur":"baslangic","gecikme":3000},"aksiyon":{"tur":"aramaGeldi","arayan":"Sezai","numara":"cep","gorselRef":"sezai-foto"}}],"talimat":"Telefon kilitli. 3 sn sonra Sezai arar; gelen arama ekranı her şeyin üstünü kaplar. Oyuncu Kabul et ya da Reddet''e basar. Kabul edince sayaç işlemeye başlar."}'::jsonb),
  ('eg-b03-s58', 'eg', 3, '{"kod":"eg-b03-s58","cihaz":"nergis-pc","baslangic":{"modul":"sosyal","ekran":"feed","hesap":"nergis"},"durum":{"baglanti":"normal","gorsel":"normal"},"olaylar":[{"id":"post-yuklendi","ad":"Nergis post yükler","tetik":{"tur":"dokunma","hedef":"yeni-post-akisi-tamam"},"aksiyon":{"tur":"postYukle","icerikRef":"nergis-post-cicekci"}},{"id":"sezai-begeni","ad":"Sezai (sahte hesap) beğenir","tetik":{"tur":"sonra","olayId":"post-yuklendi","gecikme":5000},"aksiyon":{"tur":"begeniGeldi","hesap":"gonul-yolcusu"}},{"id":"sezai-yorum","ad":"Sezai yorum yapar","tetik":{"tur":"sonra","olayId":"sezai-begeni","gecikme":800},"aksiyon":{"tur":"yorumGeldi","hesap":"gonul-yolcusu","metin":"..."}}],"talimat":"F11 ile tam ekran. + ile post yükleme akışı. Post yüklendikten 5 sn sonra Sezai''nin sahte hesabından beğeni ve yorum gelir."}'::jsonb),
  ('eg-b03-s59', 'eg', 3, '{"kod":"eg-b03-s59","cihaz":"nergis-telefon","baslangic":{"modul":"sosyal","ekran":"yorumlar","hesap":"nergis","icerikRef":"nergis-post-cicekci"},"durum":{"baglanti":"normal","gorsel":"normal"},"olaylar":[{"id":"sezai-yorumu","ad":"Sezai''nin yorumu ekranda durur","tetik":{"tur":"baslangic","gecikme":0},"aksiyon":{"tur":"yorumGeldi","hesap":"gonul-yolcusu","metin":"Yeni başlangıçlar hayırlı olsun.","postRef":"nergis-post-cicekci"}},{"id":"yazmaya-basla","ad":"Nergis yorum alanına dokunur, klavye açılır","tetik":{"tur":"dokunma","hedef":"yorum-alani"},"aksiyon":{"tur":"ghostTypingBaslat","hedef":"yorum-yaz","metin":"Teşekkürler, çok naziksiniz 🌿","mod":"senaryolu"}},{"id":"nergis-yorumu","ad":"Nergis yorumu paylaşır","tetik":{"tur":"dokunma","hedef":"yorum-gonderildi"},"aksiyon":{"tur":"yorumGeldi","hesap":"nergis","metin":"Teşekkürler, çok naziksiniz 🌿","postRef":"nergis-post-cicekci"}}],"talimat":"Yorumlar ekranı açık. Oyuncu ekrana bir kez dokunur, klavye açılır. Sonra KLAVYEDE İSTEDİĞİ TUŞLARA BASAR — senaryodaki metin kendiliğinden yazılır. Metin bitince Paylaş aktifleşir. Replikler senaryodan alınmalı; buradakiler yer tutucudur."}'::jsonb),
  ('eg-b03-s62', 'eg', 3, '{"kod":"eg-b03-s62","cihaz":"nergis-telefon","baslangic":{"modul":"arama","ekran":"ana","icerikRef":"arama-kadikoy-kahvalti"},"durum":{"baglanti":"normal","gorsel":"normal"},"olaylar":[{"id":"yazmaya-basla","ad":"Nergis arama çubuğuna dokunur, klavye açılır","tetik":{"tur":"dokunma","hedef":"arama-alani"},"aksiyon":{"tur":"ghostTypingBaslat","hedef":"arama-cubugu","metin":"kadıköy sahilde kahvaltı","mod":"senaryolu"}},{"id":"sonuclar-gelir","ad":"Arama yapılır, sonuç sayfası açılır","tetik":{"tur":"dokunma","hedef":"arama-yapildi"},"aksiyon":{"tur":"ekranAc","modul":"arama","ekran":"sonuclar","icerikRef":"arama-kadikoy-kahvalti"}},{"id":"gorsellere-gec","ad":"Görseller sekmesi açılır","tetik":{"tur":"elle"},"aksiyon":{"tur":"ekranAc","modul":"arama","ekran":"gorseller","icerikRef":"arama-kadikoy-kahvalti"}},{"id":"ilk-siteye-gir","ad":"İlk sonuca dokunulur, site açılır","tetik":{"tur":"dokunma","hedef":"arama-sonuc-1"},"aksiyon":{"tur":"ekranAc","modul":"web","ekran":"sayfa","icerikRef":"site-kiyida-sabah"}},{"id":"ikinci-siteye-gir","ad":"İkinci sonuca dokunulur, blog açılır","tetik":{"tur":"dokunma","hedef":"arama-sonuc-2"},"aksiyon":{"tur":"ekranAc","modul":"web","ekran":"sayfa","icerikRef":"site-gezgin-notu"}},{"id":"foruma-gir","ad":"Dördüncü sonuca dokunulur, forum açılır","tetik":{"tur":"dokunma","hedef":"arama-sonuc-4"},"aksiyon":{"tur":"ekranAc","modul":"web","ekran":"sayfa","icerikRef":"site-rehber-defteri"}}],"talimat":"LOOK arama sayfası açık. Oyuncu arama çubuğuna dokunur, klavye açılır; KLAVYEDE İSTEDİĞİ TUŞLARA BASAR — senaryodaki metin kendiliğinden yazılır. Metin bitince alttaki ara düğmesi aktifleşir; basınca sonuç sayfası gelir. Sonuçlardan birine dokununca o site açılır (1. sonuç işletme sayfası, 2. sonuç blog, 4. sonuç forum; 3. sonucun sitesi yok). Görseller sekmesi gerekiyorsa kumandadan tetiklenir. Aranan metin, sonuçlar ve site içerikleri senaryodan alınmalı; buradakiler yer tutucudur. SAHNE NUMARASI GEÇİCİ: gerçek numara yapımdan gelince değiştirilecek."}'::jsonb),
  ('eg-b03-s63', 'eg', 3, '{"kod":"eg-b03-s63","cihaz":"nergis-telefon","baslangic":{"modul":"telefon","ekran":"gecmis"},"durum":{"baglanti":"normal","gorsel":"normal","saat":"23:44"},"olaylar":[{"id":"sezai-arar","ad":"Sezai arar — gelen arama ekranı üstü kaplar","tetik":{"tur":"baslangic","gecikme":4000},"aksiyon":{"tur":"aramaGeldi","arayan":"Sezai","numara":"cep","gorselRef":"sezai-foto"}},{"id":"numara-yazilir","ad":"Tuş takımı açılır, numara kendiliğinden yazılır","tetik":{"tur":"dokunma","hedef":"telefon-tus"},"aksiyon":{"tur":"ghostTypingBaslat","hedef":"telefon-numara","metin":"0532 000 00 12","mod":"senaryolu"}}],"talimat":"Telefon uygulaması Son Aramalar ekranında açık. 4 sn sonra Sezai arar; gelen arama ekranı üstü kaplar. Oyuncu reddedince arama geçmişinin başına yeni bir ''gelen'' kaydı düşer. Oyuncu Tuş Takımı sekmesine geçerse tuşlara bastıkça senaryodaki numara kendiliğinden yazılır; yeşil düğme giden arama ekranını açar. Rehber ve geçmiş cihaz dosyasından gelir; isimler ve numaralar yer tutucudur. SAHNE NUMARASI GEÇİCİ: gerçek numara yapımdan gelince değiştirilecek."}'::jsonb),
  ('eg-b03-s71', 'eg', 3, '{"kod":"eg-b03-s71","cihaz":"sezai-telefon","baslangic":{"modul":"kilit","ekran":"kilit"},"durum":{"baglanti":"normal","gorsel":"normal","pil":14},"olaylar":[{"id":"pil-dustu","ad":"Pil %5''e düşer","tetik":{"tur":"baslangic","gecikme":2500},"aksiyon":{"tur":"pilDegisti","seviye":5}},{"id":"pil-kritik","ad":"Pil %1''e düşer","tetik":{"tur":"sonra","olayId":"pil-dustu","gecikme":7000},"aksiyon":{"tur":"pilDegisti","seviye":1}},{"id":"telefon-kapandi","ad":"Telefon kapanır","tetik":{"tur":"sonra","olayId":"pil-kritik","gecikme":5000},"aksiyon":{"tur":"pilDegisti","seviye":0}}],"talimat":"Telefon kilitli, pil %14. 2,5 sn sonra %5 (uyarı çıkar), 7 sn sonra %1, 5 sn sonra telefon kapanır. Kapanma anı elle tetiklenerek replikaya denk getirilebilir."}'::jsonb)
on conflict (kod) do update set
  dizi = excluded.dizi,
  bolum = excluded.bolum,
  veri = excluded.veri;

commit;
